# Generated by Django 4.2.27 on 2025-12-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('load_description', models.CharField(max_length=200)),
                ('origin_address', models.CharField(max_length=300)),
                ('destination_address', models.CharField(max_length=300)),
                ('overall_length_ft', models.PositiveIntegerField(default=0)),
                ('overall_length_in', models.PositiveIntegerField(default=0)),
                ('overall_width_ft', models.PositiveIntegerField(default=0)),
                ('overall_width_in', models.PositiveIntegerField(default=0)),
                ('overall_height_ft', models.PositiveIntegerField(default=0)),
                ('overall_height_in', models.PositiveIntegerField(default=0)),
                ('gross_weight', models.PositiveIntegerField(default=0, help_text='Gross weight in lbs')),
                ('front_overhang_ft', models.PositiveIntegerField(default=0)),
                ('front_overhang_in', models.PositiveIntegerField(default=0)),
                ('rear_overhang_ft', models.PositiveIntegerField(default=0)),
                ('rear_overhang_in', models.PositiveIntegerField(default=0)),
                ('left_overhang_ft', models.PositiveIntegerField(default=0)),
                ('left_overhang_in', models.PositiveIntegerField(default=0)),
                ('right_overhang_ft', models.PositiveIntegerField(default=0)),
                ('right_overhang_in', models.PositiveIntegerField(default=0)),
                ('axle_configuration', models.PositiveIntegerField(default=1)),
                ('num_axles', models.PositiveIntegerField(default=0)),
                ('is_legal_weight', models.BooleanField(default=False)),
                ('customer_comments', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permits', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_requests', to='company.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.paymentmethod')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_permits', to=settings.AUTH_USER_MODEL)),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_as_trailer', to='fleet.vehicle')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_as_truck', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('permit', 'Permit'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='permit_documents/')),
                ('filename', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='permits.permitrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermitComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments not visible to customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='permits.permitrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('route', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='permits.permitrequest')),
            ],
            options={
                'ordering': ['state'],
                'unique_together': {('permit', 'state')},
            },
        ),
        migrations.CreateModel(
            name='PermitAxleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_number', models.PositiveIntegerField()),
                ('spacing_ft', models.PositiveIntegerField(default=0)),
                ('spacing_in', models.PositiveIntegerField(default=0)),
                ('weight_lbs', models.PositiveIntegerField(default=0)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axle_details', to='permits.permitrequest')),
            ],
            options={
                'ordering': ['axle_number'],
                'unique_together': {('permit', 'axle_number')},
            },
        ),
    ]
