# Generated by Django 4.2.27 on 2026-01-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='load_make_model',
            field=models.CharField(blank=True, max_length=200, verbose_name='Make/Model'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_serial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Serial#'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='load_description',
            field=models.CharField(max_length=200, verbose_name='Object/Load Description'),
        ),
    ]
