# Generated by Django 4.2.27 on 2026-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_permitrequest_load_make_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_1',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-1 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_2',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-2 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_3',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-3 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_4',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-4 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_5',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-5 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_6',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-6 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_7',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-7 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_8',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-8 Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='axle_weight_9',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ax-9 Weight'),
        ),
    ]
