# Generated by Django 4.2.27 on 2026-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_permitrequest_axle_weight_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='load_height',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_length',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_weight',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_width',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='load_description',
            field=models.CharField(max_length=200, verbose_name='Cargo/Load Description'),
        ),
    ]
