# Generated by Django 4.2.27 on 2026-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_permitrequest_load_height_permitrequest_load_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_1_2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 1-2'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_2_3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 2-3'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_3_4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 3-4'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_4_5',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 4-5'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_5_6',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 5-6'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_6_7',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 6-7'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_7_8',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 7-8'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='spacing_8_9',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Spacing 8-9'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_1',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-1'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_2',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-2'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_3',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-3'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_4',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-4'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_5',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-5'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_6',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-6'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_7',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-7'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_8',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-8'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='tires_per_axle_9',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Tires Ax-9'),
        ),
    ]
