# Generated by Django 4.2.27 on 2026-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_permitrequest_spacing_1_2_permitrequest_spacing_2_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='load_detailed_description',
            field=models.TextField(blank=True, verbose_name='Detailed Load Description'),
        ),
    ]
