# Generated by Django 4.2.27 on 2026-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_permitrequest_load_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='kingpin_to_rear_ft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='kingpin_to_rear_in',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
