# Generated by Django 4.2.27 on 2026-01-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_permitrequest_kingpin_to_rear_ft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitstate',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='permitstate',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
