# Generated by Django 4.2.27 on 2026-01-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_alter_permitstate_options_permitstate_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitrequest',
            name='load_height',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='load_length',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='load_width',
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_height_ft',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Height (ft)'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_height_in',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Height (in)'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_length_ft',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Length (ft)'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_length_in',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Length (in)'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_width_ft',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Width (ft)'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='load_width_in',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Width (in)'),
        ),
    ]
