# Generated by Django 4.2.27 on 2026-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_remove_permitrequest_load_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='kingpin_to_rear_axle_ft',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Kingpin to Rear Axle (ft)'),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='kingpin_to_rear_axle_in',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Kingpin to Rear Axle (in)'),
        ),
    ]
