# Generated by Django 4.2.27 on 2026-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_permitrequest_kingpin_to_rear_axle_ft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitrequest',
            name='kingpin_to_rear_axle_ft',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='kingpin_to_rear_axle_in',
        ),
    ]
