# Generated by Django 4.2.27 on 2025-12-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_number', models.PositiveIntegerField(default=1)),
                ('num_axles', models.PositiveIntegerField(default=0, verbose_name='Number of Axles')),
            ],
            options={
                'ordering': ['configuration_number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('trailer', 'Trailer')], max_length=10)),
                ('unit_number', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('plate_state', models.CharField(blank=True, max_length=2)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN')),
                ('length_ft', models.PositiveIntegerField(default=0, verbose_name='Length (ft)')),
                ('length_in', models.PositiveIntegerField(default=0, verbose_name='Length (in)')),
                ('registration_pdf', models.FileField(blank=True, null=True, upload_to='registrations/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='company.company')),
            ],
            options={
                'ordering': ['unit_number'],
                'unique_together': {('company', 'unit_number', 'vehicle_type')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_state', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='company.company')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AxleWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_number', models.PositiveIntegerField()),
                ('weight_lbs', models.PositiveIntegerField(default=0)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='fleet.axleconfiguration')),
            ],
            options={
                'ordering': ['axle_number'],
            },
        ),
        migrations.CreateModel(
            name='AxleSpacing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_number', models.PositiveIntegerField()),
                ('spacing_ft', models.PositiveIntegerField(default=0)),
                ('spacing_in', models.PositiveIntegerField(default=0)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spacings', to='fleet.axleconfiguration')),
            ],
            options={
                'ordering': ['axle_number'],
            },
        ),
        migrations.AddField(
            model_name='axleconfiguration',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axle_configurations', to='fleet.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='axleconfiguration',
            unique_together={('vehicle', 'configuration_number')},
        ),
    ]
