# Generated by Django 4.2.27 on 2026-01-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this combination (e.g., 'John's Regular Setup')", max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Use this as default for new permits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_combinations', to='company.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('trailer', models.ForeignKey(blank=True, limit_choices_to={'vehicle_type': 'trailer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_combinations', to='fleet.vehicle')),
                ('truck', models.ForeignKey(blank=True, limit_choices_to={'vehicle_type': 'truck'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_combinations', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
