# Generated by Django 4.2.27 on 2026-01-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('fleet', '0002_equipmentcombination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcombination',
            options={'ordering': ['-is_default', 'driver__last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentcombination',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='equipmentcombination',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentcombination',
            unique_together={('company', 'driver', 'truck', 'trailer')},
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='name',
        ),
    ]
