# Generated by Django 4.2.27 on 2026-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_equipmentcombination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcombination',
            name='num_axles',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_1_2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_2_3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_3_4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_4_5',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_5_6',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_6_7',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_7_8',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_8_9',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
    ]
