# Generated by Django 4.2.27 on 2026-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_equipmentcombination_num_axles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_1_2',
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_2_3',
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_3_4',
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_4_5',
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_5_6',
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_6_7',
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_7_8',
        ),
        migrations.RemoveField(
            model_name='equipmentcombination',
            name='spacing_8_9',
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_1_2_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_1_2_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_2_3_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_2_3_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_3_4_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_3_4_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_4_5_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_4_5_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_5_6_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_5_6_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_6_7_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_6_7_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_7_8_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_7_8_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_8_9_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='spacing_8_9_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
