# Generated by Django 4.2.27 on 2026-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_equipmentcombination_spacing_1_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcombination',
            name='kingpin_to_rear_axle_ft',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipmentcombination',
            name='kingpin_to_rear_axle_in',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
